### ISSUE TITLE
Wrong method to get component data for an entity in the documentation

### ISSUE THREAD

**Issue by maxailloud** [adngdb/entity-system-js#27]
On https://entity-system-js.readthedocs.io/en/latest/#components it's stated that to get the data of an entity you have to do 
```
var aPositionData = manager.getEntityWithComponent(aPosition, 'Position');
console.log(aPositionData.x);
```

But it should be 
```
var aPositionData = manager.getComponentDataForEntity('Position', aPosition);
console.log(aPositionData.x);
```

No idea how to fix the documentation by myself so here we are.

**Comment by adngdb** [comment]
Thanks! The actual file in the repo is up-to-date, but for some reason readthedocs isn't. I'll take a look.

**Comment by maxailloud** [comment]
Yes I saw.
Maybe hosting it in the gh-pages could be easier.

**Comment by maxailloud** [comment]
Oh I just saw the commit fixing the documentation.

**Comment by Hectate** [comment]
This error still exists in the Processors section.
https://github.com/adngdb/entity-system-js/blob/master/docs/index.md#processors

That said; is there not a way to query the manager for all entities with a component? The example requires an entity ID to be passed to `manager.getEntityWithComponent()` but I'm looking for a way to get an array (or similar) of all entity ids that have the component assigned without knowing the IDs beforehand.

**Comment by Hectate** [comment]
Reviewing the Concentration example I came across this:
`
RenderingProcessor.prototype.initTiles = function () {
        var cards = this.manager.getComponentsData('Card');
        for (var entityId in cards) {
            this.createCardTile(entityId, cards[entityId]);
        }
};
`
Is that the recommended approach?

**Comment by adngdb** [comment]
@Hectate Yes, `getComponentsData` is how to get all entities that have the specified component. In version 1.5.0, that method returns an object of `entityID` -> `componentData`. Thanks for noticing the mismatch in documentation, I'm on it!
