### ISSUE TITLE
[Idea] Having a way of creating an entity with an initial state

### ISSUE THREAD

**Issue by maxailloud** [adngdb/entity-system-js#36]
What do you think of a way to create an entity with an initial state?
By with an initial state I mean something like :
`let entity = manager.createEntity(['MyComponent'], initialState);`

I know the `createEntity` has the entityId as second parameter so it could be a third optional parameter. Or maybe a new method that will use the `intialState` value as default value for the entity's components.

My use case is that I am working on https://github.com/adngdb/entity-system-js/issues/24 and being able to create an entity with an initial state will allow, using the create event, to manage more clearly the creation of the an framework related objects (Phaser in my case) when one is linked to an other. 

My use case is with Phaser when you deal with `ParticleEmitter` you need a `ParticleEmitterManager` to actually create your emitter. So for that I need to create my manager and give it's entityId to my ParticleEmitter. I did it and it works https://github.com/maxailloud/phangular/blob/ensy-events/src/app/scenes/main.scene.ts#L58. However in my rendering processor I need to plan for the case when my emitter doesn't have a manager attached to it when i create it, something that cannot exist as in Phaser the emitter is created by a manager. 

So for my case having an initial state for my entity will make the code for my rendering processor way cleaner as I won't have to deal with 2 different cases, one with and one without the manager entityId I need to create my emitter.

Same thing when an object follows (in any way) an other object, having an initial value makes you able to make it directly.

I hope I was clear enough so you can understand what I mean.
Of course if you think that could be a good addition to ensy I will see to make it happen.

**Comment by adngdb** [comment]
That sounds good to me! As long as you don't break the API, and just add a new parameter to that function, I don't mind.

**Comment by maxailloud** [comment]
Oh yeah for sure the API will just be enhanced let's say, not modified.
Ok so will do.
